### PR TITLE
Feature/models

### PR DESCRIPTION
**Pull request by zhemalb**
All issues resolved

### CODE REVIEW

**Review by crystalixxx — COMMENTED** [review]
Some comments:
1) In schemas.py no need users field in Tag, because in class that field loads dynamic with SQLAlchemy 'relationship' (it's just auto join with user table) and it doesn't need in schemas which use in CRUD operations
2) Current version of Tag doesn't support representation by rgba format (in field in models.py this field have constraint by 7 length)
3) Need to add pytest to test_file.py

**Review by crystalixxx — COMMENTED** [review]
And delete or finish schema for HackathonBase model, it doesn't contain all field

**Comment by zhemalb** [comment]
1. Users field removed.
2. Switched from the rgba format to the usual rgb format.
3. Pytest support added in test_file.py.
4. HackathonBase model schema finished.

**Comment by zhemalb** [comment]
Removed Pytest for now because it was causing issues

**Review by crystalixxx — APPROVED** [review]

**Pull request merged**
